[window]

opacity = 0.8
blur = true

padding.x = 10
padding.y = 10

decorations = "None"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family = "JetBrainsMono NF"
bold.family = "JetBrainsMono NF"
italic.family = "JetBrainsMono NF"
bold_italic.family = "JetBrainsMono NF"

size = 13.0

[cursor]
style = { shape = "Beam", blinking = "Always"}
vi_mode_style = { shape = "Beam", blinking = "Always"}
blink_timeout = 0
unfocused_hollow = false

[colors]
[colors.primary]
background = "#1a1b26"
foreground = "#ffffff"

[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"

[colors.bright]
black = "#444b6a"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7da6ff"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#acb0d0"
