#!/bin/sh
# Description: Script to get battery status

# Grab the volume information from wpctl
vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

# If muted, print 🔇 and exit.
[ "$vol" != "${vol%\[MUTED\]}" ] && echo "  0%" && exit

# Extract the volume percentage and store it in the percent variable
percent=$(echo "$vol" | awk -F': ' '{print $2}' | awk '{print $1 * 100}')

# Determine the volume icon based on the volume percentage
if [ "$percent" -ge 50 ]; then
    icon_volume="   "
elif [ "$percent" -ge 25 ]; then
    icon_volume="  "
elif [ "$percent" -ge 1 ]; then
    icon_volume="  "
else
    icon_volume="  "
fi

# Print the volume icon and percentage
printf "%s%s%%\n" "$icon_volume" "$percent"
exit 0
